kind: pipeline
type: docker
name: default

steps:

- name: Docker image 
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USER
    password:
      from_secret: DOCKER_TOKEN
    repo: getais/mermaid-server
    tags: latest      
